/**
 * Preflop helpers built on the precomputed class-vs-class equity matrix.
 *
 * Matrix: E(i, j) = all-in preflop equity of hand class i vs class j, averaged uniformly over
 * card-disjoint combo pairs, generated by scripts/generate-preflop-matrix.ts with the engine's
 * own Monte Carlo (see `MATRIX_INFO` for trials and max standard error). E(i, i) = 1/2 exactly by
 * symmetry, and E(j, i) = 1 − E(i, j).
 *
 * Approximation used by the "fast" functions below: a combo's equity against another combo is
 * replaced by the average of their classes (suit interactions such as a shared flush suit are
 * averaged out). Card removal between the two combos IS respected exactly. For exact numbers use
 * the equity engine; the UI labels matrix-based numbers accordingly.
 */
import matrixData from './data/preflopMatrix.json'
import { COMBO_CARDS, COMBO_CLASS, HAND_CLASSES, NUM_CLASSES, NUM_COMBOS, combosOverlap, type HandClass } from './combos'
import { deadFlags, type Card } from './cards'
import type { Weights } from './range'

const N = NUM_CLASSES

export const MATRIX_INFO = {
  trialsPerPair: matrixData.trialsPerPair as number,
  maxStdError: matrixData.maxStdError as number,
  method: matrixData.method as string,
}

/** Full 169x169 equity table, Float64Array row-major. */
export const PREFLOP_EQUITY: Float64Array = (() => {
  const values = matrixData.values as number[]
  if (values.length !== (N * (N + 1)) / 2) throw new Error('preflopMatrix.json has the wrong size')
  const m = new Float64Array(N * N)
  let k = 0
  for (let i = 0; i < N; i++) {
    for (let j = i; j < N; j++) {
      const e = i === j ? 0.5 : values[k] / 1e5
      m[i * N + j] = e
      m[j * N + i] = 1 - e
      k++
    }
  }
  return m
})()

export function classVsClass(i: number, j: number): number {
  return PREFLOP_EQUITY[i * N + j]
}

/**
 * Number of card-disjoint combo pairs between two classes (e.g. AA vs AKs: 6·4 − overlaps = 12... see test).
 */
export function disjointPairCount(a: HandClass, b: HandClass): number {
  let n = 0
  for (const c of a.combos) for (const d of b.combos) if (!combosOverlap(c, d)) n++
  return n
}

/**
 * Equity of each hero combo vs a villain range (fast, matrix-based), respecting card removal
 * between the two hands and against `dead` cards. Returns per-combo equity (NaN if no villain combo fits)
 * and the weight of villain combos that fit.
 */
export function comboEquitiesVsRange(villain: Weights, dead: readonly Card[] = []): { equity: Float64Array; weight: Float64Array } {
  const d = deadFlags(dead)
  const vIdx: number[] = []
  for (let v = 0; v < NUM_COMBOS; v++) {
    if (villain[v] > 0 && !d[COMBO_CARDS[2 * v]] && !d[COMBO_CARDS[2 * v + 1]]) vIdx.push(v)
  }
  const equity = new Float64Array(NUM_COMBOS)
  const weight = new Float64Array(NUM_COMBOS)
  for (let h = 0; h < NUM_COMBOS; h++) {
    const a = COMBO_CARDS[2 * h], b = COMBO_CARDS[2 * h + 1]
    if (d[a] || d[b]) { equity[h] = NaN; continue }
    const row = COMBO_CLASS[h] * N
    let acc = 0, tot = 0
    for (const v of vIdx) {
      const c = COMBO_CARDS[2 * v], e = COMBO_CARDS[2 * v + 1]
      if (c === a || c === b || e === a || e === b) continue
      const w = villain[v]
      acc += w * PREFLOP_EQUITY[row + COMBO_CLASS[v]]
      tot += w
    }
    equity[h] = tot > 0 ? acc / tot : NaN
    weight[h] = tot
  }
  return { equity, weight }
}

/**
 * Per-class equity vs a villain range (fast, matrix-based): the average over the class's live combos,
 * each weighted by how many villain combos it can face. NaN when no combo of the class is possible.
 */
export function classEquitiesVsRange(villain: Weights, dead: readonly Card[] = []): Float64Array {
  const { equity, weight } = comboEquitiesVsRange(villain, dead)
  const out = new Float64Array(N)
  for (const cls of HAND_CLASSES) {
    let acc = 0, tot = 0
    for (const c of cls.combos) {
      if (Number.isNaN(equity[c]) || weight[c] === 0) continue
      acc += equity[c] * weight[c]
      tot += weight[c]
    }
    out[cls.index] = tot > 0 ? acc / tot : NaN
  }
  return out
}

/**
 * Range vs range equity (fast, matrix-based): Σ w_h w_v E(h, v) / Σ w_h w_v over disjoint pairs.
 */
export function rangeVsRangeFast(hero: Weights, villain: Weights, dead: readonly Card[] = []): number {
  const { equity, weight } = comboEquitiesVsRange(villain, dead)
  let acc = 0
  let tot = 0
  for (let h = 0; h < NUM_COMBOS; h++) {
    if (hero[h] <= 0 || Number.isNaN(equity[h]) || weight[h] === 0) continue
    const w = hero[h] * weight[h]
    acc += w * equity[h]
    tot += w
  }
  return tot > 0 ? acc / tot : NaN
}

/** Equity of each class vs a uniformly random hand (matrix-based). */
export const EQUITY_VS_RANDOM: Float64Array = (() => {
  const any = new Float64Array(NUM_COMBOS).fill(1)
  return classEquitiesVsRange(any)
})()

/**
 * The 169 classes ordered from strongest to weakest by equity vs a random hand.
 * (One of several possible orderings; used for "top X%" ranges and bot profiles.)
 */
export const CLASS_RANKING: number[] = Array.from({ length: N }, (_, i) => i)
  .sort((a, b) => EQUITY_VS_RANDOM[b] - EQUITY_VS_RANDOM[a])

/**
 * Top X% of starting hands by the ranking above. Classes are added whole while they fit; the
 * boundary class gets a partial weight so the combo total is exactly `fraction` · 1326.
 */
export function topPercentRange(fraction: number, ranking: number[] = CLASS_RANKING): Weights {
  const r = new Float64Array(NUM_COMBOS)
  let remaining = Math.max(0, Math.min(1, fraction)) * NUM_COMBOS
  for (const idx of ranking) {
    if (remaining <= 1e-9) break
    const cls = HAND_CLASSES[idx]
    const n = cls.combos.length
    const w = Math.min(1, remaining / n)
    for (const c of cls.combos) r[c] = w
    remaining -= w * n
  }
  return r
}

// ---------------------------------------------------------------------------------------------
// Preflop categories (mutually exclusive, first match wins)
// ---------------------------------------------------------------------------------------------
export interface PreflopCategory {
  id: string
  label: string
  test: (c: HandClass) => boolean
}

const TEN = 8
export const PREFLOP_CATEGORIES: PreflopCategory[] = [
  { id: 'high-pairs', label: 'High pairs (TT+)', test: (c) => c.kind === 'pair' && c.high >= TEN },
  { id: 'mid-pairs', label: 'Middle pairs (66–99)', test: (c) => c.kind === 'pair' && c.high >= 4 },
  { id: 'low-pairs', label: 'Low pairs (22–55)', test: (c) => c.kind === 'pair' },
  { id: 'suited-broadways', label: 'Suited broadways', test: (c) => c.kind === 'suited' && c.low >= TEN },
  { id: 'offsuit-broadways', label: 'Offsuit broadways', test: (c) => c.kind === 'offsuit' && c.low >= TEN },
  { id: 'suited-aces', label: 'Suited aces (A9s–A2s)', test: (c) => c.kind === 'suited' && c.high === 12 },
  { id: 'suited-connectors', label: 'Suited connectors', test: (c) => c.kind === 'suited' && (c.high - c.low === 1) },
  { id: 'suited-gappers', label: 'Suited one/two-gappers', test: (c) => c.kind === 'suited' && (c.high - c.low === 2 || c.high - c.low === 3) },
  { id: 'other-suited', label: 'Other suited', test: (c) => c.kind === 'suited' },
  { id: 'offsuit-aces', label: 'Offsuit aces (A9o–A2o)', test: (c) => c.kind === 'offsuit' && c.high === 12 },
  { id: 'offsuit-connectors', label: 'Offsuit connectors', test: (c) => c.kind === 'offsuit' && c.high - c.low === 1 },
  { id: 'other-offsuit', label: 'Other offsuit', test: (c) => c.kind === 'offsuit' },
]

export const CLASS_CATEGORY: string[] = HAND_CLASSES.map((c) => PREFLOP_CATEGORIES.find((cat) => cat.test(c))!.id)

export interface CategoryBreakdownRow {
  id: string
  label: string
  /** Weighted combos of the range in this category (after card removal). */
  combos: number
  /** Share of the range's combos. */
  shareOfRange: number
  /** Share of the category's total possible combos that the range contains. */
  shareOfCategory: number
}

export function categoryBreakdown(r: Weights, dead: readonly Card[] = []): CategoryBreakdownRow[] {
  const d = deadFlags(dead)
  const inRange = new Map<string, number>()
  const possible = new Map<string, number>()
  let total = 0
  for (let i = 0; i < NUM_COMBOS; i++) {
    if (d[COMBO_CARDS[2 * i]] || d[COMBO_CARDS[2 * i + 1]]) continue
    const cat = CLASS_CATEGORY[COMBO_CLASS[i]]
    possible.set(cat, (possible.get(cat) ?? 0) + 1)
    if (r[i] > 0) {
      inRange.set(cat, (inRange.get(cat) ?? 0) + r[i])
      total += r[i]
    }
  }
  return PREFLOP_CATEGORIES.map((cat) => {
    const combos = inRange.get(cat.id) ?? 0
    return {
      id: cat.id,
      label: cat.label,
      combos,
      shareOfRange: total > 0 ? combos / total : 0,
      shareOfCategory: (possible.get(cat.id) ?? 0) > 0 ? combos / possible.get(cat.id)! : 0,
    }
  })
}
